x-worker-template:
  worker: &worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./worker:/var/www/html
    networks:
      - backend
      - payment-processor
    # deploy:
      # resources:
        # limits:
          # cpus: "0.1"
          # memory: "50MB"

services:

  worker1:
    <<: *worker
    container_name: worker1

  worker2:
    <<: *worker
    container_name: worker2

  nginx:
    image: openresty/openresty:1.25.3.1-1-bullseye
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/handler.lua:/usr/local/openresty/nginx/lua/handler.lua
    ports:
      - "9999:80"
    depends_on:
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
